### ISSUE TITLE
Footer stretches with overflow

### ISSUE THREAD

**Issue by cassidyjames** [Nerwyn/material-rounded-theme#17] opened 2024-05-16 00:21 UTC
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:** 1.0

**Last working release (if known):** This has always been the case

**Browser and Operating System:** Home Assistant companion app for Android

**Description of problem:**

When I hit the edge of the scroll view on Android, the footer stretches with the overflow stretch. Instead, it should stay static.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

https://github.com/Nerwyn/material-rounded-theme/assets/611168/7421185a-2073-411e-82c7-66f116ac5b8b

**Comment by Nerwyn** [comment] 2024-05-16 01:46
Duplicate of #14. This is an issue with Home Assistant, and is present in the default theme. It has to be fixed by the Home Assistant companion app developers.

**Closed** 2024-05-16 01:46 UTC
Labels: bug
