### ISSUE TITLE
Dashboard title overlapping with menu icon

### ISSUE THREAD

**Issue by ZOXSOCKS** [Nerwyn/material-rounded-theme#25] opened 2024-07-29 07:57 UTC
**Checklist:**

-   [x ] I updated to the latest version available
-   [x ] I cleared the cache of my browser

**Release with the issue:**
2.1.0-beta.003

**Browser and Operating System:**
Home assistant companion app
Vivaldi (chromium)
Android 14
Pixel 7 Pro 
1440 x 3120 resolution 

**Description of problem:**
The title of the dashboard pops under the navigation drawer menu icon on the mobile browser. (And on desktop browser with the window resized to a mobile resolution).

Title of the dashboard also visibly pops under the menu icon on page load.

Page title should sit next to the menu icon, not under it.

![Screenshot_20240729-083241](https://github.com/user-attachments/assets/bbd5a6ea-2209-47a9-9fa3-1311aaa37381)

https://github.com/user-attachments/assets/bf7757ac-ac6e-4577-b36d-59853fa84901

**Comment by Nerwyn** [comment] 2024-07-29 13:27
How are you making the dashboard title appear on non subviews? It doesn't appear on any of my lovelace or sections views.

**Comment by ZOXSOCKS** [comment] 2024-07-29 13:46
It's taking it from the title of the dashboard. If I change the title, it changes it on the dashboard, and keeps it buried under the menu button.

![Screenshot_20240729-144511](https://github.com/user-attachments/assets/6b4161b3-466a-4ec1-be3d-917dcab07556)

**Comment by Nerwyn** [comment] 2024-07-29 13:48
That's weird. My title's don't appear. Which version of the frontend are you on?

**Comment by ZOXSOCKS** [comment] 2024-07-29 13:51
I am on the very latest of everything HA. It might be because I'm using the sections layout rather than anything else?

**Comment by Nerwyn** [comment] 2024-07-29 13:59
Nope, I'm also using sections view now. Are you sure it isn't caused by another add-on?

**Comment by Nerwyn** [comment] 2024-07-29 14:06
I'm not seeing the view title in the view itself in the Home Assistant docs either.
https://www.home-assistant.io/dashboards/sections/

**Comment by ZOXSOCKS** [comment] 2024-07-29 14:11
I've figured out the cause of the problem. I have, at present, only one view (and one sub-view which doesn't appear on the nav bar.)

Adding a second view (just named it test for now) moves the 'home' text from the top left and puts it in the bottom nav bar where it belongs. Very odd behaviour!
![image](https://github.com/user-attachments/assets/28d91965-95e7-4a93-8ed6-b957fd549d51)

**Comment by Nerwyn** [comment] 2024-07-29 14:27
Ah I see. That's still definitely worth fixing. I'll try to get around to it later today.

**Comment by Nerwyn** [comment] 2024-07-30 00:26
I've put out another beta that should fix this. I ended up reworking and further separating our the header and footer styles and adding padding to the top to make it so that the view no longer overlaps with the header. This does make the view much smaller than default, but it's similar to how most material 3 apps are.

**Comment by xvlw** [comment] 2024-07-30 12:16
This solved an issue I had where the chip card was being covered by the hamburger on the left side on mobile devices. I was forced to add a title to my top section in order to force everything down.

Now I can remove that title and everything fits.

Beta working well for me, thank you!

**Comment by Nerwyn** [comment] 2024-08-01 00:33
Fixed in [2.1.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.0)

**Closed by Nerwyn** 2024-08-01 00:33 UTC
Labels: bug
